Handle conventionally uploaded artifacts as well.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -99,6 +99,7 @@ runs:
 
         ANSI_LIGHT_RED="\e[91m"
         ANSI_LIGHT_GREEN="\e[92m"
+        ANSI_LIGHT_YELLOW="\e[93m"
         ANSI_NOCOLOR="\e[0m"
 
         if [[ "${{ inputs.name }}" == "" ]]; then
@@ -110,12 +111,20 @@ runs:
         for artifactDirectory in "${artifactDirectories[@]}"; do
           pushd "${artifactDirectory}" > /dev/null
         
-          echo -n "Extracting tarball '${artifactDirectory}/${{ inputs.tarball-name }}' ... "
-          tar -xf "${{ inputs.tarball-name }}"
-          if [[ $? -ne 0 ]]; then
-            echo -e "${ANSI_LIGHT_RED}[FAILED]${ANSI_NOCOLOR}"
+          echo -n "Checking tarball '${artifactDirectory}/${{ inputs.tarball-name }}' ... "
+          if [[ -f "${{ inputs.tarball-name }}" ]]; then
+            echo -e "${ANSI_LIGHT_GREEN}[FOUND]${ANSI_NOCOLOR}"
+        
+            echo -n "Extracting tarball '${artifactDirectory}/${{ inputs.tarball-name }}' ... "
+            tar -xf "${{ inputs.tarball-name }}"
+            if [[ $? -ne 0 ]]; then
+              echo -e "${ANSI_LIGHT_RED}[FAILED]${ANSI_NOCOLOR}"
+            else
+              echo -e "${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
+            fi
           else
-            echo -e "${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
+            echo -e "${ANSI_LIGHT_YELLOW}[MISSING]${ANSI_NOCOLOR}"
+            echo "  → assuming artifact was uploaded by actions/upload-artifact"
           fi
           
           popd > /dev/null
