Check artifact downloaded into a directory.

diff --git a/.github/workflows/ArtifactsDownload.yml b/.github/workflows/ArtifactsDownload.yml
--- a/.github/workflows/ArtifactsDownload.yml
+++ b/.github/workflows/ArtifactsDownload.yml
@@ -6,7 +6,7 @@ on:
 
 jobs:
   Build-1:
-    name: Upload artifact
+    name: Build 1 - Upload artifact
     runs-on: ubuntu-24.04
 
     steps:
@@ -38,8 +38,43 @@ jobs:
 #          if-no-files-found: error
 #          retention-days: 1
 
+  Build-2:
+    name: Build 2 - Upload artifact
+    runs-on: ubuntu-24.04
+
+    steps:
+      - name: 🖉 Build 2
+        run: |
+          echo "Document 1 $(date --utc '+%d.%m.%Y - %H:%M:%S')"   > document1.txt
+          echo "Analysis log $(date --utc '+%d.%m.%Y - %H:%M:%S')" > analysis.log
+          echo "Build log $(date --utc '+%d.%m.%Y - %H:%M:%S')"    > build.log
+          
+          mkdir -p bin
+          echo "Program $(date --utc '+%d.%m.%Y - %H:%M:%S')"   > bin/program.py
+          chmod u+x bin/program.py
+          
+          mkdir -p lib
+          echo "Library $(date --utc '+%d.%m.%Y - %H:%M:%S')"   > lib/common.py
+          chmod +x lib/common.py
+
+      - name: 🔎 Inspect directory structure
+        run: |
+          tree .
+
+      - name: 📤 Upload artifact
+        uses: pyTooling/upload-artifact@dev
+        with:
+          name: release-2
+          path: |
+            document1.txt
+            *.log
+            bin/
+            lib/*.py
+#          if-no-files-found: error
+#          retention-days: 1
+
   Verify-1:
-    name: Verify artifact content
+    name: Verify 1 - Artifact content
     runs-on: ubuntu-24.04
     needs:
       - Build-1
@@ -63,7 +98,7 @@ jobs:
           ANSI_NOCOLOR="\e[0m"
           
           echo "List directory content"
-          ls -lAh . 
+          ls -lAh .
           echo "----------------------------------------"
           
           echo -n "Was tarball removed ... "
@@ -109,3 +144,141 @@ jobs:
           else
             echo -e "${ANSI_LIGHT_GREEN}No errors found.${ANSI_NOCOLOR}"
           fi
+
+      - name: 📋 Verify file permissions
+        run: |
+          set +e
+
+          ANSI_LIGHT_RED="\e[91m"
+          ANSI_LIGHT_GREEN="\e[92m"
+          ANSI_NOCOLOR="\e[0m"
+
+          expected=(
+            "bin/program.py"
+            "lib/common.py"
+          )
+
+          errors=0          
+          for file in "${expected[@]}"; do
+            echo -n "Checking '${file}' ... "
+            if [[ -x "$file" ]]; then
+              echo -e "${ANSI_LIGHT_GREEN}[PASSED]${ANSI_NOCOLOR}"
+            else
+              echo -e "${ANSI_LIGHT_RED}[FAILED]${ANSI_NOCOLOR}"
+              echo -e "${ANSI_LIGHT_RED}File '${file}' isn't executable.${ANSI_NOCOLOR}"
+              errors=$((errors + 1))
+            fi  
+          done
+          
+          echo ""
+          if [[ $errors -ne 0 ]]; then
+            echo -e "${ANSI_LIGHT_RED}Counted ${errors} errors.${ANSI_NOCOLOR}"
+          else
+            echo -e "${ANSI_LIGHT_GREEN}No errors found.${ANSI_NOCOLOR}"
+          fi
+
+  Verify-2:
+    name: Verify 2 - Artifact content in directory
+    runs-on: ubuntu-24.04
+    needs:
+      - Build-2
+
+    steps:
+      - name: 📥 Download artifact
+        uses: pyTooling/download-artifact@dev
+        with:
+          name: release-2
+          path: artifact
+
+      - name: 🔎 Inspect extracted artifact (tarball)
+        run: |
+          tree .
+
+      - name: 🔎 Inspect cleanup
+        run: |
+          set +e
+
+          ANSI_LIGHT_RED="\e[91m"
+          ANSI_LIGHT_GREEN="\e[92m"
+          ANSI_NOCOLOR="\e[0m"
+          
+          echo "List directory content"
+          ls -lAh .
+          echo "----------------------------------------"
+          
+          echo -n "Was tarball removed ... "
+          if [[ -f artifact/__upload_artifact__.tar ]]; then
+            echo -e "${ANSI_LIGHT_RED}[FAILED]${ANSI_NOCOLOR}"
+            echo -e "${ANSI_LIGHT_RED}Artifact's tarball 'artifact/__upload_artifact__.tar' still exists.${ANSI_NOCOLOR}"
+            exit 1
+          else
+            echo -e "${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}"
+          fi
+
+      - name: 📋 Verify extracted artifact content
+        run: |
+          set +e
+
+          ANSI_LIGHT_RED="\e[91m"
+          ANSI_LIGHT_GREEN="\e[92m"
+          ANSI_NOCOLOR="\e[0m"
+
+          expected=(
+            "artifact/document1.txt"
+            "artifact/analysis.log"
+            "artifact/build.log"
+            "artifact/bin/program.py"
+            "artifact/lib/common.py"
+          )
+
+          errors=0          
+          for file in "${expected[@]}"; do
+            echo -n "Checking '${file}' ... "
+            if [[ -f "$file" ]]; then
+              echo -e "${ANSI_LIGHT_GREEN}[PASSED]${ANSI_NOCOLOR}"
+            else
+              echo -e "${ANSI_LIGHT_RED}[FAILED]${ANSI_NOCOLOR}"
+              echo -e "${ANSI_LIGHT_RED}Extracted artifact doesn't contain file '${file}'.${ANSI_NOCOLOR}"
+              errors=$((errors + 1))
+            fi  
+          done
+          
+          echo ""
+          if [[ $errors -ne 0 ]]; then
+            echo -e "${ANSI_LIGHT_RED}Counted ${errors} errors.${ANSI_NOCOLOR}"
+          else
+            echo -e "${ANSI_LIGHT_GREEN}No errors found.${ANSI_NOCOLOR}"
+          fi
+
+      - name: 📋 Verify file permissions
+        run: |
+          set +e
+
+          ANSI_LIGHT_RED="\e[91m"
+          ANSI_LIGHT_GREEN="\e[92m"
+          ANSI_NOCOLOR="\e[0m"
+
+          expected=(
+            "artifact/bin/program.py"
+            "artifact/lib/common.py"
+          )
+
+          errors=0          
+          for file in "${expected[@]}"; do
+            echo -n "Checking '${file}' ... "
+            if [[ -x "$file" ]]; then
+              echo -e "${ANSI_LIGHT_GREEN}[PASSED]${ANSI_NOCOLOR}"
+            else
+              echo -e "${ANSI_LIGHT_RED}[FAILED]${ANSI_NOCOLOR}"
+              echo -e "${ANSI_LIGHT_RED}File '${file}' isn't executable.${ANSI_NOCOLOR}"
+              errors=$((errors + 1))
+            fi  
+          done
+          
+          echo ""
+          if [[ $errors -ne 0 ]]; then
+            echo -e "${ANSI_LIGHT_RED}Counted ${errors} errors.${ANSI_NOCOLOR}"
+          else
+            echo -e "${ANSI_LIGHT_GREEN}No errors found.${ANSI_NOCOLOR}"
+          fi
+
